### PR TITLE
allow symfony 4.0

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
This would allow symfony 4.0 for bundles/component requiring yours.

Pleas relase after green and merge.

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
@jeanmonod shall i fiix the tests or are even red on master?

**Comment by dbu** [comment]
i restarted the master branch. this smells like it would not be related to this MR, lets see: https://travis-ci.org/liip/RMT/builds/270377916

**Comment by dbu** [comment]
or not. could it have something to do with allowing symfony 4? although there are old version installs, so this should not be the reason. but master is still green...

**Comment by dbu** [comment]
interesting, there is an open bug with exactly this message: #77. although i don't see how that would be related

**Comment by ElectricMaxxx** [comment]
So lets fix it :-)

**Comment by dbu** [comment]
i did a minimal fix that i merged. can you please rebase your branch on master to see if the error goes away?

**Comment by dbu** [comment]
i also merged #131 - can you please rebase and solve conflicts?

**Comment by ElectricMaxxx** [comment]
Lets see what happens.

**Comment by ElectricMaxxx** [comment]
Looks green now :-)

**Comment by ElectricMaxxx** [comment]
@dbu can you tag a release on  then? We should see an effect on: https://github.com/doctrine/phpcr-odm/pull/764

**Pull request merged**
