### PR TITLE
Add Symfony 5 support

### PR DESCRIPTION
**Pull request by tgalopin**
#SymfonyHackday

### CODE REVIEW

**Comment by jeanmonod** [comment]
@tgalopin Thanks a lot for the contribution! I hope you are doing well!
Best, 
David

**Comment by jeanmonod** [comment]
@tgalopin 
Oh... I just see that the PR is flagged as WIP, is it still the case? Do you still want to add something?

**Comment by tgalopin** [comment]
I'm doing well, thanks :)! I hope you do too! 

I need to fix the tests, yes!

**Comment by tgalopin** [comment]
This should be green now.

Note that I dropped support for unsupported versions of Symfony, most notably because the sensiolabs/security-checker requires such versions. As it is relatively easy to migrate minor version in Symfony, this should not have much of an impact on the usage of RMT.

**Pull request merged**
