### PR TITLE
Fix errors on Symfony/Console v6.0+

### PR DESCRIPTION
**Pull request by mateuslecchi**
As I say in issue #166 I've figured out that error happens when use Symfony/Console: v6.0+, and when I upgraded my Laravel application to v9.0, that needs Symfony/Cosole: v6.0+ I face this error ever since. I think that I have fixed.

PS.: This is my first pull request, I dont know if I'm doing right.

### CODE REVIEW

**Comment by jeanmonod** [comment]
@mateuslecchi Little update on this PR:

Looking at your PR, we realized that the CI is not working since Months. We have to migrate to travis-ci.com setting up GitHub Actions. Once this done (hopefully this week). We will be able to run the CI over this PR, and if everything is green, we will merge it. Thank you for your patience

cc @Jonathanm10 @dbu

**Comment by mateuslecchi** [comment]
Thank you for the feedback, the RMT project is awesome, you guys have done a nice job.

**Comment by dbu** [comment]
hi @mateuslecchi , 
thanks for the pull request. and no worries you did it exactly right! (and even if it was not, we all learn and are happy to teach ;-) )

i continued from your command and moved the build to github actions. would you have time to check if #168 looks correct or if i messed up anything?

**Comment by jeanmonod** [comment]
@mateuslecchi as your commit have been transfert to https://github.com/liip/RMT/pull/168 by @dbu, I'm closing this PR now. I will merge and release from #168 
Thanks again for your contribution

**Comment by jeanmonod** [comment]
FYI: A new release 1.7.0 is available

**Pull request closed without merging**
