### PR TITLE
Add the phpunit requirement (build on travis with version 5.4.0)

### PR DESCRIPTION
**Pull request by sseidelmann**
Hey everybody,

I want to add a feature and checked first the unit tests. I found no reference to used phpunit version. So i added it as a dev-requirement (version used from travis build).

Greetings

### CODE REVIEW

**Comment by acrobat** [comment]
Please use a version constraint that allows supported versions of phpunit. PHPUnit 4 is eol since 3 February 2017

It's better to use this constraint:
`"phpunit/phpunit": "^5.5|^6.0"`

**Comment by sseidelmann** [comment]
Thats right. i will check the dependency and update them.

**Comment by acrobat** [comment]
I think it's better to deprecate some old (and unsupported) php versions, instead of making workarounds for phpunit versions. I will open a PR later today to propose a fix!

**Comment by sseidelmann** [comment]
Jeah that will be great, i will wait for it

**Comment by lsmith77** [comment]
you also need to adjust the script in .travis.yml to use the composer installed phpunit

**Comment by acrobat** [comment]
@lsmith77  I've create PR #124 to bump to php version and require phpunit (+ test fixes).

**Comment by sseidelmann** [comment]
I close this PR

**Pull request closed without merging**
