### PR TITLE
Fix tests with php 8

### PR DESCRIPTION
**Pull request by alekitto**
Fixed test execution with PHP 8.

PHP minimum version has been raised to 7.1 (the minimum version supported by PHPUnit 7).
Also symfony components are required to be 3.4 minimum (already EOL anyway, but not so old).

### CODE REVIEW

**Review by dbu — APPROVED** [review]
looks good to me, thanks!

i am not so sure about the assertions converted from `$this->` to `self::`, most projects i have seen keep calling it with `$this->` but i have no strong opinion on this.

@jeanmonod do you agree, shall we merge it like this?

**Comment by mathieupetrini** [comment]
any updates on this ?

**Comment by jeanmonod** [comment]
Sorry for the delay. Covid duty and then holidays 😬
That's fine for me! Let's merge it into @dbu branch and then into master

**Comment by jeanmonod** [comment]
Thanks @alekitto !

**Pull request merged**
