### PR TITLE
[TASK] Add the phpcs configuration

### PR DESCRIPTION
**Pull request by sseidelmann**
Adding the php-cs-fixer with PSR2 styleguide
To let it run:
```
vendor/bin/php-cs-fixer fix
vendor/bin/php-cs-fixer fix --dry-run
```

I also fixed two files that are not PSR2 formatted.

It would be nice to insert this into travis:
```
script:
  - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run
```

### CODE REVIEW

**Comment by jeanmonod** [comment]
Have you see the builds? There is an issue with the composer dependencies...

**Comment by acrobat** [comment]
I'm :-1: on adding this to composer. Imo php-cs-fixer should be installed locally, but this won't enforce the correct use of code style. So maybe it's an option to use a service like [styleci.io](https://styleci.io/) which will check each pr and report issues with coding style (and provide a patch file)

**Comment by sseidelmann** [comment]
@jeanmonod jeah, correct. I will check this later.

**Comment by sseidelmann** [comment]
@acrobat Can be closed maybe. See the new PR #125 for the styleci integration

**Pull request closed without merging**
