### PR TITLE
Migrate travis to GitHub actions

### PR DESCRIPTION
**Pull request by daniel-werner**
I've migrated the travis tests to GitHub actions, (I see there is another PR on this topic: https://github.com/liip/RMT/pull/168)

In this PR the tests for php8 and symfony console v6 are failing, but merging the https://github.com/liip/RMT/pull/167 fixes all the issues, I tested it in my fork.

Btw thanks for this nice tool! I use it regularly and I am very happy with it!

### CODE REVIEW

**Comment by dbu** [comment]
hi @daniel-werner , thanks for the PR. i think #168 is ready to be merged. do you want to review and see if anything is missing? i prefer using flex to lock the symfony component versions instead of having a `composer require` as the require can hide incorrect configuration in composer.json.

**Comment by daniel-werner** [comment]
@dbu I've checked https://github.com/liip/RMT/pull/168 and it seems fine to me. Closing this PR, and look forward to the next release which include these fixes. Thanks!

**Comment by jeanmonod** [comment]
@daniel-werner For your information, a new RMT release, 1.7.0 is available for the compatibility fixes. Thanks for your contribution

**Comment by daniel-werner** [comment]
@jeanmonod I am happy to hear that, thank you for the great tool!

**Pull request closed without merging**
